server:
  port: 8012
spring:
  application:
    name: crp-rule-stomach

  datasource:
    # mysql 8.0 以下
    # url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=utf8&autoReconnect=true
    # driver-class-name: com.mysql.jdbc.Driver
    # mysql 8.0 以上使用
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.20.25.100:3306/dmp_std_liver?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456

    url2: jdbc:mysql://172.20.25.100:3306/dmp_zbk_liver?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username2: root
    password2: 123456

    hiveurl: jdbc:hive2://0.0.0.0:10000/iot
    hiveusername: hive
    hivepassword: hive
    hivedriverclassname: org.apache.hive.jdbc.HiveDriver

    #type: com.alibaba.druid.pool.DruidDataSource
    #driverClassName: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://192.168.129.3:3306/dmp_sdt_stomach??useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    #username: dmp_etl
    #password: DcHealth@2020

    #url2: jdbc:mysql://192.168.129.3:3306/dm_zbk_lung?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    #username2: dmp_etl
    #password2: DcHealth@2020


shellPath: /root/nanfang_liver_zbk.sh

